<a href="https://colab.research.google.com/github/Jaikirao/Generate-Parallel-Databases/blob/master/generate_parallel_database.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

# the number of entries in our database
num_entries = 5000

db = torch.rand(num_entries) > 0.5
db

tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8)

In [0]:
def get_parallel_db(db , remove_index):
  return torch.cat((db[0:remove_index],
                    db[remove_index+1:]))

In [0]:
get_parallel_db(db,2)

tensor([1, 1, 1,  ..., 1, 1, 1], dtype=torch.uint8)

In [0]:
def get_parallel_dbs(db):
  parallel_dbs=list()
  for i in range(len(db)):
    pdb=get_parallel_db(db,i)
    parallel_dbs.append(pdb)
    
  return parallel_dbs


In [0]:
get_parallel_dbs(db)

[tensor([1, 0, 1,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 1,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 1, 1

In [0]:
def create_db_and_parallel(num_enteries):
  db=torch.rand(num_enteries)>0.5
  pdbs= get_parallel_dbs(db)
  
  return db,pdbs

In [0]:
db,pdbs =create_db_and_parallel(30)

In [0]:
db

tensor([1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
        1, 1, 1, 1, 1, 0], dtype=torch.uint8)

In [0]:
pdbs

[tensor([1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
         1, 1, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
         1, 1, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
         1, 1, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
         1, 1, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
         1, 1, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
         1, 1, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
         1, 1, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
         1, 1, 1, 1, 0], dtype=torch.